version: '3.9'

services:
  mtr:
    build: .
    environment:
      - TARGET_HOST=8.8.8.8  # 監視対象のホストを指定（デフォルトはGoogle DNS）
    volumes:
      - ./logs:/logs  # ログファイルを保存するディレクトリをマウント
    restart: always
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
        preferences:
          - spread: node.id
      # ノード間で均等に分散させるための設定
      resources:
        limits:
          cpus: '0.3'
          memory: 50M
